### ISSUE TITLE
Nothing is exported by pull

### ISSUE THREAD

**Issue by junghans** [odeke-em/drive#180]
`pull` doesn't export anything for me by default! So either https://github.com/odeke-em/drive/blob/master/README.md#exporting-docs is wrong or I found a bug.

**Comment by odeke-em** [comment]
Hello @junghans welcome to drive and thank you for reporting this issue!

Would you mind showing me your command?
One thing that might be useful to know is pull-export when your file is already consistent will yield no results since you are not actually pulling in any changes. Pass in `--force` to make it a write and don't forget to use the export flags and formats.
Please let me know if this makes sense.

**Comment by junghans** [comment]
I did an `init` followed by a `pull` and nothing got export. Using `pull --force --export pdf` works, however the next `pull` without `--force` deletes all exports. Using `--force` for every pull is not very usable as all files get download again. (btw. this is 6d9751a)

**Comment by odeke-em** [comment]
`drive pull --force --export pdf,docx,rtf my_doc` should cut the deal for you without deletions.
Even better
`drive pull --force  --exports-dir ~/Desktop/my_exports --export pdf,docx,rtf my_doc`
should prevent the clutter.
I don't see how this is a problem as long as you remember that drive tries to mirror what is on your drive.

**Comment by junghans** [comment]
The problem with `--force` is that, it re-downloads all the files every time.

**Comment by odeke-em** [comment]
Gotcha, I'll push a little patch up when I get home in about 40 minutes. Watch this space :)

**Comment by odeke-em** [comment]
@junghans please take a look at PR #181.

**Comment by odeke-em** [comment]
Addressed by PR https://github.com/odeke-em/drive/pull/181.
Please reopen if persists. Thank you for reporting this.

**Comment by junghans** [comment]
Works, thanks!

Is there a way to set the exports directory to be the current path? With `--export-dir="." directories with the name <NAME>_exports are still created. I looking for some way to backup the Google docs files as pdf without any additional directory structure and desktop files. The latter is a huge deal as they are very small and can be filtered out later.

**Comment by odeke-em** [comment]
Actually I'd rather not, this is because I'd like to minimize the clutter created by exporting documents. I would prefer it as is that if per document they are placed in the directory `document_name_exports`. In the future, you'll be able to create a defaults file or so, just like you do with a `.driveignore`.

**Comment by junghans** [comment]
For some reason the original problem is back in version cfbed7a46abb533f1b1e15431a1b1b523448db8f:
```
drive pull -export pdf
```
will re-export all files even if they are unchanged.

**Comment by odeke-em** [comment]
Wasn't the issue initially that `drive pull -export pdf` wouldn't work on unchanged exportable files?
The solution was to ensure that all exportable files are explicitly requested. This then seems like desired behaviour different from the initial issue.
Please let me know if I am missing something,

**Comment by junghans** [comment]
Ok, let me clarify. By default (in contrast to what the README.md is saying) nothing gets exported. So doing `drive pull -export pdf` in the old version (before PR #181) would do nothing, except in combination with `--force`. In cfbed7a46abb533f1b1e15431a1b1b523448db8f  `drive pull -export pdf` exports pdf, but re-does it every time even if the files are unchanged.

**Comment by odeke-em** [comment]
And this is an issue? I thought your initial issue was that -export was supposed to just work irrespective of whether the files are changed or not. This is because before PR 181 it would pull things ONLY when the content was unchanged but as you can see from the history of the issue and I think I mentioned this here https://github.com/odeke-em/drive/issues/180#issuecomment-98884754

**Comment by odeke-em** [comment]
Please pardon me if I don't seem to be understanding your issue, it doesn't help that I've been up for 18+ hours so am probably not getting you right :) If you could provide the expectations in different scenarios in some sort of point form that'd be appreciated.
Thank you.

**Comment by junghans** [comment]
I know that feeling ;-) My point was mainly that before `-force` triggered an export explicitly and now the `-force` is implicit with every `pull -export pdf`. If this behavior is desired, that is fine, I was just wondering.

**Comment by znaf** [comment]
Hi, this affects me ever since I upgraded from 0.1.2 to latest version. I have over 1000 google sheets
every time I do `drive pull  -export xls` ALL of them are being re-downloaded/ and re-exported

**Comment by odeke-em** [comment]
Okay am gotcha, sorry @junghans and @znaf for all the trouble. I can see how this is tricky with 1000 Google sheets all being exported every single time.

**Comment by odeke-em** [comment]
Addressed by PR https://github.com/odeke-em/drive/pull/230.
You can now do:

```shell
$ drive pull --export pdf,xls --explicitly-export
```
